# Generated by Django 5.2.3 on 2026-02-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onyango', '0001_initial_onyango'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, help_text='Labour price (TZS). Materials cost is added from parts used.', max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='repairpayment',
            name='materials_settled',
            field=models.BooleanField(default=False, help_text='True when materials portion has been sent to shop via TransferSettlement.'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='job_type',
            field=models.ForeignKey(blank=True, help_text='Fixed labour price. Materials cost from shop is added to invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='onyango.jobtype'),
        ),
    ]
