# Generated by Django 5.2.3 on 2026-02-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onyango', '0002_job_type_and_invoice_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfersettlement',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfersettlement',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfersettlement',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_material_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Full price (TZS): labour + expected materials. No extra charge for materials.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='repairjob',
            name='job_type',
            field=models.ForeignKey(blank=True, help_text='Fixed price (labour + materials). Materials requested from shop; when paid, materials portion goes to shop, rest to workshop.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='onyango.jobtype'),
        ),
    ]
