# Generated by Django 5.2.3 on 2025-06-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('thief', 'Thief')], default='staff', max_length=10),
        ),
    ]
