# Generated by Django 5.2.3 on 2025-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(default=20, help_text='Minimum quantity before stock is considered low.'),
        ),
    ]
