# Generated by Django 5.2.3 on 2025-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(default=5, help_text='Minimum quantity before stock is considered low.'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=20),
        ),
    ]
