# Generated by Django 5.2.3 on 2025-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_threshold_alter_stockentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
