# Generated by Django 5.2.3 on 2025-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_stockentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('thief', 'Thief')], default='cashier', max_length=10),
        ),
    ]
