# Generated by Django 5.2.3 on 2025-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_stockentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('quantity_updated', 'Quantity_updated'), ('sold', 'sold')], max_length=20),
        ),
    ]
