# Generated by Django 5.2.3 on 2025-06-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sale_status_saleitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
