# Generated by Django 5.2.3 on 2025-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_sale_is_loan_remove_sale_refund_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(default='retail', max_length=20),
        ),
    ]
