# Generated by Django 5.2.3 on 2025-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='refund_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
