# Generated by Django 5.2.3 on 2025-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sale_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('loan', 'Loan (Active)'), ('not_paid', 'Not Paid')], default='pending', max_length=20),
        ),
    ]
