# Generated by Django 5.2.3 on 2025-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_sale_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
