# Generated by Django 5.2.3 on 2025-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_sale_discount_percent_sale_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
