# Generated by Django 5.2.3 on 2025-08-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='product',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refund_amount',
        ),
        migrations.AddField(
            model_name='refund',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_refunded', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.refund')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.saleitem')),
            ],
        ),
    ]
