# Generated by Django 5.2.3 on 2025-08-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_refund_product_remove_refund_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefundItem',
        ),
    ]
