# Generated by Django 5.2.3 on 2026-02-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_create_default_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('order_created', 'Order created'), ('order_confirmed', 'Order confirmed'), ('order_rejected', 'Order rejected'), ('sale_created', 'Sale created'), ('payment_recorded', 'Payment recorded'), ('loan_payment', 'Loan payment'), ('refund_created', 'Refund created'), ('expense_created', 'Expense recorded'), ('stock_in', 'Stock in'), ('stock_out', 'Stock out'), ('stock_adjusted', 'Stock adjusted'), ('transfer_confirmed', 'Transfer confirmed'), ('transfer_settled', 'Transfer settled'), ('repair_job_created', 'Repair job created'), ('repair_job_completed', 'Repair job completed'), ('repair_job_collected', 'Repair job collected'), ('repair_payment', 'Repair payment'), ('material_request_submitted', 'Material request submitted'), ('material_request_approved', 'Material request approved'), ('material_request_rejected', 'Material request rejected'), ('purchase_order_created', 'Purchase order created'), ('goods_receipt', 'Goods received')], max_length=40)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
