# Generated by Django 5.2.3 on 2026-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_timeline_and_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed outstanding debt for this customer (TZS).', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('contractor', 'Contractor'), ('company', 'Company')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='If true, customer cannot take new loans (debt sales).'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
