# Generated by Django 5.2.3 on 2026-02-04 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_customer_credit_limit_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_closes', to='main.unit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('unit', 'date')},
            },
        ),
    ]
