# Generated by Django 5.2.3 on 2026-02-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_quote_quoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending check'), ('checked', 'Checked')], default='pending', max_length=20),
        ),
    ]
