# Generated by Django 5.2.3 on 2026-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_quote_quote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half'), ('quarter', 'Quarter')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='portion',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half'), ('quarter', 'Quarter')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_tin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
